export const availableProductsInGrocery = [
  { name: 'Rice', code: 1 },
  { name: 'Wheat', code: 2 },
  { name: 'Corn', code: 3 },
  { name: 'Potatoes', code: 4 },
  { name: 'Tomatoes', code: 5 },
  { name: 'Onions', code: 6 },
  { name: 'Garlic', code: 7 },
  { name: 'Carrots', code: 8 },
  { name: 'Salt', code: 9 },
  { name: 'Pepper', code: 10 },
  { name: 'Turmeric', code: 11 },
  { name: 'Cilantro', code: 12 },
  { name: 'Cardamom', code: 13 },
  { name: 'Coriander', code: 14 },
  { name: 'Lemon', code: 15 },
  { name: 'Lime', code: 16 },
  { name: 'Chili', code: 17 },
  { name: 'Honey', code: 18 },
  { name: 'Sugar', code: 19 },
  { name: 'Eggs', code: 20 },
  { name: 'Milk', code: 21 },
  { name: 'Cheese', code: 22 },
  { name: 'Beef', code: 23 },
  { name: 'Pork', code: 24 },
  { name: 'Chicken', code: 25 },
  { name: 'Fish', code: 26 },
];
